export const navItems = [
  {
    href: '/dashboard',
    label: 'Dashboard',
    icon: 'mdi-view-dashboard',
    roles: null,
    activeMatch: (url) => url === '/dashboard',
  },
  {
    href: '/admin/class',
    label: 'Class Manager',
    icon: 'mdi-school',
    roles: [3],
    activeMatch: (url) => url === '/admin/class',
  },
  {
    href: '/subject/manager',
    label: 'Curriculum',
    icon: 'mdi-book-open-page-variant',
    roles: [3],
    activeMatch: (url) => url === '/subject/manager',
  },
  {
    href: '/client/digital_class/live_class',
    label: 'Live Class',
    icon: 'mdi-cast',
    roles: null,
    activeMatch: (url) => url === '/client/digital_class/live_class',
  },
  {
    href: '/client/digital_class/recorded_videos',
    label: 'Recorded Video',
    icon: 'mdi-video-vintage',
    roles: null,
    activeMatch: (url) => url === '/client/digital_class/recorded_videos',
  },
  {
    href: '/assessment',
    label: 'Assessment Setup',
    icon: 'mdi-pencil',
    roles: [3],
    activeMatch: (url) => url === '/assessment',
  },
  {
    href: '/assessment/quiz_bank',
    label: 'Assessment Bank',
    icon: 'mdi-bank',
    roles: [1, 3],
    activeMatch: (url) => url === '/assessment/quiz_bank',
  },
  {
    href: '/assessment/take_quiz_index',
    label: 'Assessment Quiz',
    icon: 'mdi-comment-question',
    roles: [2],
    activeMatch: (url) => url === '/assessment/take_quiz_index',
  },
  {
    href: '/admin/payment/pricing',
    label: 'Payment Pricing',
    icon: 'mdi-currency-ngn',
    roles: [3],
    activeMatch: (url) => url === '/admin/payment/pricing',
  },
  {
    href: '/admin/payment/transactions',
    label: 'Transactions',
    icon: 'mdi-file-document-box',
    roles: [3],
    activeMatch: (url) => url === '/admin/payment/transactions',
  },
  {
    href: '/attendance/index',
    label: 'Attendance',
    icon: 'mdi-calendar-check',
    roles: null,
    activeMatch: (url) => url.startsWith('/attendance'),
  },
  {
    href: '/profile',
    label: 'Profile',
    icon: 'mdi-account-circle',
    roles: null,
    activeMatch: (url) => url.startsWith('/profile'),
  },
  {
    href: '/purchases',
    label: 'My Purchases',
    icon: 'mdi-cart',
    roles: [2],
    activeMatch: (url) => url === '/purchases',
  },
  {
    href: '/manage-user',
    label: 'Manage Users',
    icon: 'mdi-account-group',
    roles: [3],
    activeMatch: (url) => url === '/manage-user',
  },
];
